{% set name = "fractopo" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fractopo-{{ version }}.tar.gz
  sha256: ef68197574b2366f70e4ee339ddf793c8489dc60358d2eb01fc01a00ca59ff08

build:
  number: 0
  noarch: python
  entry_points:
    - fractopo = fractopo.__main__:APP
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.1,<2
  run:
    - click
    - geopandas >=1.0.0
    - matplotlib-base >=3.5.3
    - numpy >=1.26.0,<2.0.0
    - pandas >=1.3,<3.0.0
    - powerlaw
    - python >={{ python_min }},<3.13
    - python-ternary
    - rich >=11.0.0
    - scikit-learn
    - scipy >=1.9.1
    - seaborn
    - shapely >=2.0.0,<3.0.0
    - typer >=0.4.0
    - joblib >=1.2.0

test:
  imports:
    - fractopo
    - fractopo.analysis
  commands:
    - pip check
    - fractopo --help
    - fractopo network --help
    - fractopo tracevalidate --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nialov/fractopo
  summary: Fracture Network Analysis
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://fractopo.readthedocs.io/en/latest/
  dev_url: https://github.com/nialov/fractopo

extra:
  recipe-maintainers:
    - nialov
