{% set name = "fractopo" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fractopo-{{ version }}.tar.gz
  sha256: e6be789cd26df5f916b7ebffe305885b51a9434d55976cc23020f448cc2b305b

build:
  number: 0
  noarch: python
  entry_points:
    - tracevalidate = fractopo.cli:tracevalidate
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7.1,<4.0
    - poetry >=1.1,<2
  run:
    - click
    - descartes
    - geopandas ==0.9.0
    - matplotlib-base
    - numpy
    - pandas >=1.3,<1.4
    - powerlaw
    - pygeos ==0.10.1
    - python >=3.6,<4.0
    - python-ternary
    - scipy
    - seaborn
    - shapely >=1.7,<1.8
    - scikit-learn

test:
  imports:
    - fractopo
    - fractopo.analysis
  commands:
    - pip check
    - tracevalidate --help
  requires:
    - pip

about:
  home: https://github.com/nialov/fractopo
  summary: Fracture Network Analysis
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://fractopo.readthedocs.io/en/latest/
  dev_url: https://github.com/nialov/fractopo

extra:
  recipe-maintainers:
    - nialov
