{% set name = "fractopo" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fractopo-{{ version }}.tar.gz
  sha256: fbdc1d3bb8897bc2476cfc49e03784f85019a5a0faab6e4e30e5ea5814a0b172

build:
  number: 0
  noarch: python
  entry_points:
    - fractopo = fractopo.__main__:APP
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - poetry >=1.1,<2
  run:
    - click
    - geopandas >=0.11.1,<1.0.0
    - matplotlib-base >=3.5.3
    - numpy
    - pandas >=1.3,<2.0.0
    - powerlaw
    - pygeos >=0.13.0,<1.0.0
    - python >=3.8,<3.12
    - python-ternary
    - rich >=11.0.0
    - scikit-learn
    - scipy >=1.9.1,<2.0.0
    - seaborn
    - shapely >=2.0.0,<3.0.0
    - typer >=0.4.0,<1.0.0
    - joblib >=1.2.0,<2.0.0

test:
  imports:
    - fractopo
    - fractopo.analysis
  commands:
    - pip check
    - fractopo --help
    - fractopo network --help
    - fractopo tracevalidate --help
  requires:
    - pip

about:
  home: https://github.com/nialov/fractopo
  summary: Fracture Network Analysis
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://fractopo.readthedocs.io/en/latest/
  dev_url: https://github.com/nialov/fractopo

extra:
  recipe-maintainers:
    - nialov
