{% set name = "fractopo" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fractopo-{{ version }}.tar.gz
  sha256: a943636fe724ad0be34b80cc1c3a175de2dc315fed8f4b2696a154d6fa65227b

build:
  number: 0
  noarch: python
  entry_points:
    - tracevalidate = fractopo.cli:tracevalidate_click
    - fractopo = fractopo.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7.1,<4.0
    - poetry >=1.1,<2
  run:
    - click
    - descartes
    - geopandas ==0.9.0
    - matplotlib-base
    - numpy
    - pandas >=1.3,<1.4
    - powerlaw
    - pygeos ==0.10.1
    - python >=3.6,<4.0
    - python-ternary
    - rich >=10.7.0,<11.0.0
    - scikit-learn
    - scipy
    - seaborn
    - shapely >=1.7,<1.8
    - typer >=0.3.2,<0.4.0

test:
  imports:
    - fractopo
    - fractopo.analysis
  commands:
    - pip check
    - fractopo --help
    - tracevalidate --help
  requires:
    - pip

about:
  home: https://github.com/nialov/fractopo
  summary: Fracture Network Analysis
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://fractopo.readthedocs.io/en/latest/
  dev_url: https://github.com/nialov/fractopo

extra:
  recipe-maintainers:
    - nialov
