{% set name = "fractopo" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fractopo-{{ version }}.tar.gz
  sha256: 8c8ed4fcb905c3fccd4666273bae74b2fb3a2176669cd486cae7e54745ad70ef

build:
  number: 0
  noarch: python
  entry_points:
    - fractopo = fractopo.cli:app
    - tracevalidate = fractopo.cli:tracevalidate_click
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<3.12
    - poetry >=1.1,<2
  run:
    - click
    - geopandas >=0.11.1,<0.12.0
    - matplotlib-base
    - numpy
    - pandas >=1.3,<1.4
    - powerlaw
    - pygeos >=0.13.0,<0.14.0
    - python >=3.8,<3.12
    - python-ternary
    - rich >=11.0.0,<11.1.0
    - scikit-learn
    - scipy >=1.9.1,<1.10.0
    - seaborn
    - shapely >=1.8.0,<1.9.0
    - typer >=0.4.0,<0.5.0

test:
  imports:
    - fractopo
    - fractopo.analysis
  commands:
    - pip check
    - fractopo --help
    - fractopo network --help
    - fractopo tracevalidate --help
    - tracevalidate --help
  requires:
    - pip

about:
  home: https://github.com/nialov/fractopo
  summary: Fracture Network Analysis
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://fractopo.readthedocs.io/en/latest/
  dev_url: https://github.com/nialov/fractopo

extra:
  recipe-maintainers:
    - nialov
